import type { VideoResource } from '../constants.types'

export const LANGUAGE_VIDEOS: VideoResource[] = [
  {
    id: 'a661a464-721',
    title: 'TypeScript for Professionals',
    description:
      'Types, generics, narrowing, and patterns that scale with a real codebase.',
    topic: 'typescript',
    author: 'freeCodeCamp',
    duration: '5h 09m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=30LWjhZzg50',
  },
  {
    id: '368eb5c5-76e',
    title: 'Complete TypeScript Course for Beginners',
    description: '',
    topic: 'typescript',
    author: 'Sangam Mukherjee',
    duration: '5h 30m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/W3G4DuchKFY/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=W3G4DuchKFY',
  },
  {
    id: 'cb452a3f-1a1',
    title: 'Python Tutorials',
    description: 'Gold standard for learning python',
    topic: 'python',
    author: 'Corey Schafer',
    duration: '158 Videos',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/YYXdXT2l-Gg/maxresdefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU',
  },
  {
    id: 'a76d4496-740',
    title: 'How to Golang',
    description: 'Collection of concepts in Go. Not a sequential series!',
    topic: 'go',
    author: 'Anthony GG',
    duration: '93 Videos',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/-gW7oSFxT2I/maxresdefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PL0xRBLFXXsP7-0IVCmoo2FEWBrQzfH2l8',
  },

  {
    id: '723c5ee3-f07',
    title: 'Golang Full Course 2026',
    description: '',
    topic: 'go',
    author: 'Sangam Mukherjee',
    duration: '10h 01m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/DR4QhvIlFfQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=DR4QhvIlFfQ&t=21593s',
  },
  {
    id: '716f4c54-56e',
    title: 'Go Programming – Golang Course with Bonus Projects',
    description: '',
    topic: 'go',
    author: 'Boot Dev',
    duration: '9h 32m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/un6ZyFkqFKo/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=un6ZyFkqFKo',
  },

  {
    id: '9cb742ac-f48',
    title: 'The C++ Programming Language',
    description: 'Basics to Advanced',
    topic: 'cpp',
    author: 'Mike Shah',
    duration: '250 Videos',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/LGOgNqkRMs0/sddefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PLvv0ScY6vfd8j-tlhYVPYgiIyXduu6m-L',
  },

  {
    id: 'ad4367e3-6be',
    title: 'Rust Bootcamp Part 1',
    description: '',
    topic: 'rust',
    author: 'Harkirat Singh',
    duration: '4h 1m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/qP7LzZqGh30/sddefault.jpg',
    url: 'https://www.youtube.com/watch?v=qP7LzZqGh30',
  },

  {
    id: '88398304-684',
    title: 'Rust Bootcamp Part 2',
    description: '',
    topic: 'rust',
    author: 'Harkirat Singh',
    duration: '6h 20m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/joCFbTJt0o0/sddefault.jpg',
    url: 'https://www.youtube.com/watch?v=joCFbTJt0o0',
  },
]
