import type { VideoResource } from '../constants.types'

export const LANGUAGE_VIDEOS: VideoResource[] = [
  {
    id: 2,
    title: 'TypeScript for Professionals',
    description:
      'Types, generics, narrowing, and patterns that scale with a real codebase.',
    topic: 'typescript',
    author: 'freeCodeCamp',
    duration: '5h 09m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=30LWjhZzg50',
  },
  {
    id: 10,
    title: 'Complete TypeScript Course for Beginners',
    description: '',
    topic: 'typescript',
    author: 'Sangam Mukherjee',
    duration: '5h 30m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/W3G4DuchKFY/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=W3G4DuchKFY',
  },
  {
    id: 14,
    title: 'Python Tutorials',
    description: 'Gold standard for learning python',
    topic: 'python',
    author: 'Corey Schafer',
    duration: '158 Videos',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/YYXdXT2l-Gg/maxresdefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU',
  },
  {
    id: 27,
    title: 'How to Golang',
    description: 'Collection of concepts in Go. Not a sequential series!',
    topic: 'go',
    author: 'Anthony GG',
    duration: '93 Videos',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/-gW7oSFxT2I/maxresdefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PL0xRBLFXXsP7-0IVCmoo2FEWBrQzfH2l8',
  },

  {
    id: 26,
    title: 'Golang Full Course 2026',
    description: '',
    topic: 'go',
    author: 'Sangam Mukherjee',
    duration: '10h 01m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/DR4QhvIlFfQ/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=DR4QhvIlFfQ&t=21593s',
  },
  {
    id: 28,
    title: 'Go Programming – Golang Course with Bonus Projects',
    description: '',
    topic: 'go',
    author: 'Boot Dev',
    duration: '9h 32m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/un6ZyFkqFKo/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=un6ZyFkqFKo',
  },

  {
    id: 29,
    title: 'The C++ Programming Language',
    description: 'Basics to Advanced',
    topic: 'cpp',
    author: 'Mike Shah',
    duration: '250 Videos',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/LGOgNqkRMs0/sddefault.jpg',
    url: 'https://www.youtube.com/playlist?list=PLvv0ScY6vfd8j-tlhYVPYgiIyXduu6m-L',
  },
]
