import type { VideoResource } from './constants.types'

// Placeholder content. Replace or extend these objects as your library grows.
export const VIDEO_RESOURCES: VideoResource[] = [
  {
    id: 1,
    title: 'JavaScript: The Hard Parts',
    description:
      'A durable mental model for closures, callbacks, and asynchronous JavaScript.',
    topic: 'javascript',
    author: 'Frontend Masters',
    duration: '9h 14m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/Bv_5Zv5c-Ts/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=Bv_5Zv5c-Ts',
  },
  {
    id: 2,
    title: 'TypeScript for Professionals',
    description:
      'Types, generics, narrowing, and patterns that scale with a real codebase.',
    topic: 'typescript',
    author: 'freeCodeCamp',
    duration: '5h 09m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=30LWjhZzg50',
  },
  {
    id: 3,
    title: 'React Full Course',
    description:
      'Modern React fundamentals through useful interfaces, hooks, and reusable components.',
    topic: 'react',
    author: 'Scrimba',
    duration: '11h 55m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/bMknfKXIFA8/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
  },
  {
    id: 4,
    title: 'Node.js and Express',
    description:
      'From the event loop to a production-minded API with middleware and authentication.',
    topic: 'express',
    author: 'freeCodeCamp',
    duration: '8h 16m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/Oe421EPjeBE/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
  },
  {
    id: 5,
    title: 'CSS for JavaScript Developers',
    description:
      'Layout, positioning, responsive design, and the browser rules behind polished interfaces.',
    topic: 'css',
    author: 'Kevin Powell',
    duration: '1h 03m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/OXGznpKZ_sA/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=OXGznpKZ_sA',
  },
  {
    id: 6,
    title: 'PostgreSQL in One Course',
    description:
      'Relational databases, queries, joins, indexes, and practical schema design.',
    topic: 'postgresql',
    author: 'Amigoscode',
    duration: '4h 19m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/SpfIwlAYaKk/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=SpfIwlAYaKk',
  },
  {
    id: 7,
    title: 'System Design Fundamentals',
    description:
      'Scaling, caching, load balancing, queues, and the tradeoffs behind each choice.',
    topic: 'system-design',
    author: 'ByteByteGo',
    duration: '1h 07m',
    level: 'Advanced',
    thumbnail: 'https://i.ytimg.com/vi/m8Icp_Cid5o/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=m8Icp_Cid5o',
  },
  // {
  //   id: 8,
  //   title: 'Docker in 100 Seconds',
  //   description:
  //     'A fast orientation to images, containers, Dockerfiles, and why teams use them.',
  //   topic: 'docker',
  //   author: 'Fireship',
  //   duration: '2m 46s',
  //   level: 'Beginner',
  //   thumbnail: 'https://i.ytimg.com/vi/Gjnup-PuquQ/maxresdefault.jpg',
  //   url: 'https://www.youtube.com/watch?v=Gjnup-PuquQ',
  // },
  {
    id: 9,
    title: 'Git and GitHub for Beginners',
    description:
      'Commits, branches, remotes, pull requests, and resolving common conflicts.',
    topic: 'git',
    author: 'freeCodeCamp',
    duration: '1h 08m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/RGOj5yH7evk/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
  },
  {
    id: 10,
    title: 'Complete TypeScript Course for Beginners',
    description: '',
    topic: 'typescript',
    author: 'Sangam Mukherjee',
    duration: '5h 30m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/W3G4DuchKFY/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=W3G4DuchKFY',
  },
  {
    id: 11,
    title: 'Docker Full Course with Gitlab CI CD | Learn Docker in 2 hrs',
    description:
      'A fast orientation to images, containers, Dockerfiles, and why teams use them.',
    topic: 'docker',
    author: 'Samgam Mukherjee',
    duration: '2h 10m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/-FHyCgiaxkc/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=-FHyCgiaxkc',
  },
  {
    id: 12,
    title: ' Ansible Full Course | Zero to Hero',
    description: '',
    topic: 'ansible',
    author: 'Rahul Wagh',
    duration: '3h 22m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/GROqwFFLl3s/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=GROqwFFLl3s',
  },

  {
    id: 13,
    title: 'Modern Svelte Kit - Complete Svelte Kit Course for Beginners',
    description: '',
    topic: 'svelte',
    author: 'Scott Tolinski',
    duration: '3h 01m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/vkXxFfGwPao/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=vkXxFfGwPao',
  },

  {
    id: 14,
    title: 'Python Tutorials',
    description: 'Gold standard for learning python',
    topic: 'python',
    author: 'Corey Schafer',
    duration: '158 Videos',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/YYXdXT2l-Gg/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=YYXdXT2l-Gg&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU',
  },
  {
    id: 15,
    title: 'Redis Full Course 2026 | Caching, Rate Limiting, Pub/Sub',
    description: '',
    topic: 'redis',
    author: 'Sangam Mukherjee',
    duration: '2h 18m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/hFNnNVawHhk/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=hFNnNVawHhk',
  },
  {
    id: 16,
    title:
      'QUIT Struggling with Git! My 3.5-Hour GitHub Blueprint (Beginner to Pro)',
    description:
      'A complete Git and GitHub workflow covering fundamentals through advanced collaboration.',
    topic: 'git',
    author: 'Rahul Wagh',
    duration: '3h 21m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/GTFaLDXag08/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=GTFaLDXag08',
  },
  {
    id: 17,
    title: 'Learn Git - Full Course for Beginners',
    description:
      'A beginner-friendly course covering repositories, commits, branches, merges, and remote workflows.',
    topic: 'git',
    author: 'freeCodeCamp.org',
    duration: '3h 43m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/zTjRZNkhiEU/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=zTjRZNkhiEU',
  },
  {
    id: 18,
    title: 'Nest JS Full Course 2025 | Node JS Full Course | Part 4',
    description:
      'A long-form NestJS course focused on building structured Node.js backend applications.',
    topic: 'nestjs',
    author: 'Sangam Mukherjee',
    duration: '6h 32m',
    level: 'Intermediate',
    thumbnail: 'https://i.ytimg.com/vi/XVZ10uFY9DU/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=XVZ10uFY9DU&t=8941s',
  },
  {
    id: 19,
    title:
      'NestJS Full Course for Beginners in 2026 | Build a Production-Ready API',
    description:
      'Build a production-oriented API while learning NestJS modules, services, controllers, and persistence.',
    topic: 'nestjs',
    author: 'JavaScript Mastery',
    duration: '1h 46m',
    level: 'Beginner',
    thumbnail: 'https://i.ytimg.com/vi/Q6NpiIp-6WM/maxresdefault.jpg',
    url: 'https://www.youtube.com/watch?v=Q6NpiIp-6WM&t=5703s',
  },
]
